In [4]:
import numpy as np
#generate point 
array_P1 = np.random.randint(10000, size=(11000000, 2))

np.savetxt(fname = "/Users/boyazhou/Desktop/CS561_ATD/HW3/Dataset_HW3/P1_point.txt" , X = array_P1,fmt='%i', delimiter = ',')

print array_P1

print "finish"

[[9027 9590]
 [9954 2152]
 [8710 4239]
 ..., 
 [9771 2201]
 [7583 6542]
 [9009 6573]]
finish


In [6]:
#generate rectangular
#array_P2 = np.random.randint(9980, size=(5000000, 2))
import numpy as np

array_P2 = np.random.randint(9980, size=(4200000, 2))
array_P2_new = np.array(array_P2)
print array_P2

for row in array_P2_new:
    length = np.random.randint(21,size=1)
    width = np.random.randint(6,size=1)
    row[0] = row[0] + length
    row[1] = row[1] + width
    

    
array_P2_num = []
i=1
for i in range(4200000):
    array_P2_num.append("r"+str(i))
    

array_P2_num_new = np.array(array_P2_num)



array_retangular = np.column_stack((array_P2_num_new,array_P2,array_P2_new))

np.savetxt(fname = "/Users/boyazhou/Desktop/CS561_ATD/HW3/Dataset_HW3/P1_regtangular.txt" , 
           X = array_retangular,fmt='%s', delimiter = ',')

print "finish"

[[6923 1557]
 [4440 4934]
 [ 674 4103]
 ..., 
 [ 723 1756]
 [8498 4772]
 [4324  209]]
finish


In [7]:
import numpy as np
#generate k initial points 
array_P1 = np.random.randint(10000, size=(20, 2))

np.savetxt(fname = "/Users/boyazhou/Desktop/CS561_ATD/HW3/Dataset_HW3/P3_initial_point.txt" , 
           X = array_P1,fmt='%i', delimiter = ',')

print array_P1

print "finish"

[[4236 9902]
 [1481 5378]
 [5585 2985]
 [9730 3995]
 [7685   62]
 [3776 5471]
 [5462 9069]
 [3298 5568]
 [ 765 8089]
 [8335 2763]
 [5377 9914]
 [1706 4031]
 [7886  943]
 [1659 8683]
 [4037 6123]
 [8787 5934]
 [4003 2643]
 [1064 9317]
 [9610 9720]
 [1827 9065]]
finish


In [44]:
import numpy as np
import random, string
import json
import pandas as pd
#customID:incremental
#Name:random in 100 character
#Address:random 100 in character 
#Salary:[100:1000]
#Gender:male or female

#generate 5 col seperately and change to np.array
array_customID = []
i=0
for i in range(320000):
    array_customID.append(i)
    
array_customID_np = np.array(array_customID)

array_saraly_np = np.random.randint(low=100,high=1000, size=(320000, 1))

array_gender = []
i=0
for i in range(320000):
    if np.random.randint(low=0,high=2, size=(1, 1)) == 1:
        array_gender.append("male")
    else:
        array_gender.append("female")
    
array_gender_np = np.array(array_gender)

def randomword(length):
    return  ''.join(random.choice(string.lowercase) for i in range(length))


array_name = []
i=0
for i in range(320000):
    array_name.append(randomword(100))

array_name_np = np.array(array_name)
    
array_address = []
i=0
for i in range(320000):
    array_address.append(randomword(100))
    
array_address_np=np.array(array_address)

#put all col together
array_all_np = np.column_stack((array_customID_np,array_name_np,array_address_np,array_saraly_np,array_gender_np))

array_all_pd = pd.DataFrame(array_all_np,columns=['Customer ID', 'Name', 'Address', 'Salary', 'Gender'])

array_all_json = array_all_pd.to_json(orient='records')

parsed = json.loads(array_all_json)
parsed_json = json.dumps(parsed, indent=4,sort_keys=True)

with open('/Users/boyazhou/Desktop/CS561_ATD/HW3/Dataset_HW3/DataSet_P2/Custom_json.txt', 'w') as outfile:
    outfile.write(parsed_json)
    
print "finish"

finish


In [20]:
import pandas as pd
